# Generated by Django 4.1.3 on 2022-12-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vinNumber", models.CharField(max_length=100)),
                ("stockNumber", models.IntegerField()),
                ("vehiclePrice", models.IntegerField()),
                ("tradeInPrice", models.IntegerField()),
                ("downPayment", models.IntegerField()),
                ("vehicleMileage", models.IntegerField()),
                ("make", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("trim", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("color", models.CharField(max_length=100)),
                ("fuelType", models.CharField(max_length=100)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
