# Generated by Django 4.1.3 on 2022-12-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_vehicleinformation"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Dealer",
        ),
        migrations.AlterModelOptions(
            name="vehicleinformation",
            options={"ordering": ["-updated", "-created"]},
        ),
        migrations.AddField(
            model_name="vehicleinformation",
            name="status",
            field=models.CharField(default="Pending", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="vehicleinformation",
            name="downPayment",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vehicleinformation",
            name="stockNumber",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vehicleinformation",
            name="tradeInPrice",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
