# Generated by Django 4.1.4 on 2023-02-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_customerinformation_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicleinformation",
            name="downPayment",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="vehicleinformation",
            name="stockNumber",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="vehicleinformation",
            name="tradeInMileage",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="vehicleinformation",
            name="tradeInPrice",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="vehicleinformation",
            name="vehicleMileage",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="vehicleinformation",
            name="vehiclePrice",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="vehicleinformation",
            name="year",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
