# Generated by Django 4.1.4 on 2022-12-30 19:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_customerinformation_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerinformation",
            name="social_insurance_number",
            field=models.CharField(default=django.utils.timezone.now, max_length=9),
            preserve_default=False,
        ),
    ]
