# Generated by Django 4.1.4 on 2023-02-16 23:40

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_vehicleinformation_downpayment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicleinformation",
            name="customer",
        ),
        migrations.AddField(
            model_name="vehicleinformation",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vehicleinformation",
            name="address_line_2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vehicleinformation",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vehicleinformation",
            name="company_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vehicleinformation",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicleinformation",
            name="drivers_license",
            field=models.FileField(blank=True, null=True, upload_to="drivers_licenses"),
        ),
        migrations.AddField(
            model_name="vehicleinformation",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="vehicleinformation",
            name="employment_length",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vehicleinformation",
            name="employment_status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vehicleinformation",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vehicleinformation",
            name="job_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vehicleinformation",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vehicleinformation",
            name="monthly_income",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vehicleinformation",
            name="other_income",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vehicleinformation",
            name="paystub_file",
            field=models.FileField(blank=True, null=True, upload_to="paystubs"),
        ),
        migrations.AddField(
            model_name="vehicleinformation",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
        migrations.AddField(
            model_name="vehicleinformation",
            name="postal_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vehicleinformation",
            name="province",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vehicleinformation",
            name="salary",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vehicleinformation",
            name="social_insurance_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vehicleinformation",
            name="tax_return",
            field=models.FileField(blank=True, null=True, upload_to="tax_returns"),
        ),
        migrations.DeleteModel(
            name="CustomerInformation",
        ),
    ]
