# Generated by Django 4.1.7 on 2023-04-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_remove_customervehicle_dealer_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="dealer",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
