# Generated by Django 4.1.3 on 2022-12-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_delete_dealer_alter_vehicleinformation_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicleinformation",
            name="status",
            field=models.CharField(default="Pending", editable="true", max_length=100),
        ),
    ]
