# Generated by Django 4.1.7 on 2023-03-17 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_customervehicle_down_payment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customervehicle",
            name="dealer_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dealer_vehicles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
