# Generated by Django 4.1.4 on 2022-12-31 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_customerinformation_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerinformation",
            name="employment_length",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
