# Generated by Django 4.1.7 on 2023-03-08 21:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="customervehicle",
            name="color",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customervehicle",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customervehicle",
            name="exampleDocument1",
            field=models.FileField(
                blank=True, null=True, upload_to="example_document1"
            ),
        ),
        migrations.AddField(
            model_name="customervehicle",
            name="exampleDocument2",
            field=models.FileField(
                blank=True, null=True, upload_to="example_document2"
            ),
        ),
        migrations.AddField(
            model_name="customervehicle",
            name="status",
            field=models.CharField(
                blank=True, default="pending", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="customervehicle",
            name="stockNumber",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customervehicle",
            name="tradeInColor",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customervehicle",
            name="tradeInMake",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customervehicle",
            name="tradeInMileage",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customervehicle",
            name="tradeInModel",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customervehicle",
            name="tradeInPrice",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customervehicle",
            name="tradeInTrim",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customervehicle",
            name="tradeInVin",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customervehicle",
            name="tradeInYear",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customervehicle",
            name="trim",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customervehicle",
            name="vehicleBack",
            field=models.FileField(blank=True, null=True, upload_to="vehicle_back"),
        ),
        migrations.AddField(
            model_name="customervehicle",
            name="vehicleFront",
            field=models.FileField(blank=True, null=True, upload_to="vehicle_front"),
        ),
        migrations.AddField(
            model_name="customervehicle",
            name="vehicleInterior",
            field=models.FileField(blank=True, null=True, upload_to="vehicle_interior"),
        ),
        migrations.AddField(
            model_name="customervehicle",
            name="vehicleMileage",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customervehicle",
            name="vehicleOdometer",
            field=models.FileField(blank=True, null=True, upload_to="vehicle_odometer"),
        ),
        migrations.AddField(
            model_name="customervehicle",
            name="vehiclePrice",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customervehicle",
            name="vehicleSide",
            field=models.FileField(blank=True, null=True, upload_to="vehicle_side"),
        ),
        migrations.AddField(
            model_name="customervehicle",
            name="vinNumber",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
