# Generated by Django 4.1.7 on 2023-04-18 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_user_dealer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customervehicle",
            name="dealer_name",
        ),
        migrations.AddField(
            model_name="customervehicle",
            name="dealer_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nondealer_customers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="customervehicle",
            name="dealer",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="dealer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customers",
                to="base.dealer",
            ),
        ),
    ]
