# Generated by Django 4.1.3 on 2022-12-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_vehicleinformation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicleinformation",
            name="status",
            field=models.CharField(
                blank=True, default="Pending", editable="true", max_length=100
            ),
        ),
    ]
