# Generated by Django 4.1.4 on 2023-01-05 16:48

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_customerinformation_employment_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerinformation",
            name="address_line_2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customerinformation",
            name="employment_length",
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customerinformation",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=15, region=None
            ),
        ),
    ]
