# Generated by Django 4.1.4 on 2023-01-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_customerinformation_address_line_2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerinformation",
            name="paystub_file",
            field=models.FileField(blank=True, null=True, upload_to="pay_stubs/"),
        ),
        migrations.AlterField(
            model_name="customerinformation",
            name="tax_return",
            field=models.FileField(blank=True, null=True, upload_to="tax_returns/"),
        ),
    ]
