# Generated by Django 4.1.7 on 2023-04-19 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_remove_vehicleinformation_dealership_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicleinformation",
            name="Dealership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.dealership",
            ),
        ),
        migrations.AddField(
            model_name="vehicleinformation",
            name="dealer_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dealer_submitted_vehicle",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
