# Generated by Django 4.1.7 on 2023-04-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_vehicleinformation_dealer_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dealer_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
