# Generated by Django 4.1.7 on 2023-04-19 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_vehicleinformation_dealership_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customervehicle",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_vehicle",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
