# Generated by Django 4.1.7 on 2023-04-19 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_alter_customervehicle_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalDocuments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "tax_return",
                    models.FileField(blank=True, null=True, upload_to="tax_return"),
                ),
                (
                    "paystub",
                    models.FileField(blank=True, null=True, upload_to="paystub"),
                ),
                (
                    "additional_documents",
                    models.FileField(
                        blank=True, null=True, upload_to="additional_documents"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
