# Generated by Django 4.1.7 on 2023-04-08 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_alter_user_dealer_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="dealer_id",
        ),
    ]
