# Generated by Django 4.1.7 on 2023-04-19 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_rename_user_additionaldocuments_customervehicle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionaldocuments",
            name="customervehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.customervehicle"
            ),
        ),
    ]
