# Generated by Django 4.1.7 on 2023-04-12 21:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_dealer_customervehicle_dealer_user_dealer"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealer",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
