# Generated by Django 4.1.7 on 2023-04-13 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_dealer_created"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customervehicle",
            name="dealer_user",
        ),
        migrations.RemoveField(
            model_name="user",
            name="dealer_name",
        ),
        migrations.AlterField(
            model_name="customervehicle",
            name="dealer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dealer_vehicles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
