# Generated by Django 4.1.7 on 2023-04-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_customervehicle_progress_vehicleinformation_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customervehicle",
            name="status",
            field=models.CharField(
                blank=True, default="PENDING", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="vehicleinformation",
            name="status",
            field=models.CharField(
                blank=True, default="PENDING", max_length=100, null=True
            ),
        ),
    ]
