# Generated by Django 4.1.7 on 2023-04-15 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_user_dealer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customervehicle",
            name="dealer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customers",
                to="base.customervehicle",
            ),
        ),
    ]
