# Generated by Django 4.2 on 2023-05-04 00:48

from django.db import migrations, models
import virtualcargeeks.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0015_alter_customervehicle_progress_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="drivers_license",
            field=models.FileField(
                blank=True,
                null=True,
                storage=virtualcargeeks.storage_backends.PrivateS3Boto3Storage(),
                upload_to="vehicles",
            ),
        ),
    ]
